---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: stackmap-consumer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: stackmap-consumer
  template: 
    metadata:
      labels:
        app: stackmap-consumer
    spec:
      containers:
        - name: stackmap-consumer
          image: stackmap-consumer:latest
          imagePullPolicy: Never
          env:
          - name: MAPDATA_ROOT
            value: /data/
          - name: PSQL_HOST
            value: stackmap-db-postgresql.default.svc.cluster.local
              #            value: postgresql.default.svc.cluster.local
          - name: PSQL_PORT
            value: "5432"
          - name: PSQL_USER
            value: postgres
          - name: PSQL_DB
            value: postgres 
          - name: PSQL_PASS
            valueFrom:
              secretKeyRef:
                name: stackmap-db-postgresql
                key: postgres-password
          - name: RABBITMQ_HOST
            value: stackmap-rabbitmq.default.svc.cluster.local
          - name: RABBITMQ_PASS
            valueFrom:
              secretKeyRef:
                name: stackmap-rabbitmq
                key: rabbitmq-password

          volumeMounts:
            # name must match the volume name below
            - name: nfs
              mountPath: "/data/"
              #- name: host-mount
              #mountPath: "/src2/"
      volumes:
       - name: nfs
         persistentVolumeClaim:
           claimName: nfs
           #- name: host-mount
           #hostPath: 
           #path: "/home/eysteinn/tmp/"
           #type: Directory

       
---


apiVersion: v1
kind: Service
metadata:
  name: stackmap-consumer
spec:
  type: ClusterIP
  selector:
    app: stackmap-consumer
  ports:
  - protocol: TCP
    port: 3333
    targetPort: 3333
    #nodePort: 3000


