---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: stackmap-consumer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: stackmap-consumer
  template: 
    metadata:
      labels:
        app: stackmap-consumer
    spec:
      imagePullSecrets:
      - name: ghcr-login-secret
      containers:
        - name: stackmap-consumer
          #image: stackmap-consumer:latest
          #imagePullPolicy: IfNotPresent
          image: ghcr.io/eysteinn/stackmap-consumer:latest
          imagePullPolicy: Always

          env:
          - name: MAPDATA_ROOT
            value: /data/
          - name: PSQL_HOST
            value: stackmap-db-postgresql.default.svc.cluster.local
              #            value: postgresql.default.svc.cluster.local
          - name: PSQL_PORT
            value: "5432"
          - name: PSQL_USER
            value: postgres
          - name: PSQL_DB
            value: postgres 
          - name: PSQL_PASS
            valueFrom:
              secretKeyRef:
                name: stackmap-db-postgresql
                key: postgres-password
          - name: RABBITMQ_HOST
            value: stackmap-rabbitmq.default.svc.cluster.local
          - name: RABBITMQ_PASS
            valueFrom:
              secretKeyRef:
                name: stackmap-rabbitmq
                key: rabbitmq-password

          volumeMounts:
            # name must match the volume name below
            - name: nfs
              mountPath: "/data/"
              #- name: host-mount
              #mountPath: "/src2/"
      volumes:
       - name: nfs
         persistentVolumeClaim:
           claimName: nfs
           #- name: host-mount
           #hostPath: 
           #path: "/home/eysteinn/tmp/"
           #type: Directory

       
---


apiVersion: v1
kind: Service
metadata:
  name: stackmap-consumer
spec:
  type: ClusterIP
  selector:
    app: stackmap-consumer
  ports:
  - protocol: TCP
    port: 3333
    targetPort: 3333
    #nodePort: 3000


---

apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: consumer
spec:
  entryPoints:
    - web
  routes:
    - match: Host(`stackmap.clouds.is`) && PathPrefix(`/api/v1/projects/{[A-Za-z0-9_]+}/files`)
      kind: Rule
      services:
        - name: stackmap-consumer
          port: 3333

    - match: Host(`stackmap.clouds.is`) && PathPrefix(`/api/v1/projects/{[A-Za-z0-9_]+}/products/{[A-Za-z0-9_]+}/files`)
      kind: Rule
      services:
        - name: stackmap-consumer
          port: 3333

